import type { Metadata } from "next";
import Header from "@/components/ui/custom/common/Header";


export const metadata: Metadata = {
  title: "TrendiQ - Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
